### ISSUE TITLE
Warning about link-initialize.js script embedded more than once

### ISSUE THREAD

**Issue by rblakejohnson** [plaid/react-plaid-link#107]
I'm submitting this issue as reopening #103 
I updated to 2.1.2 as @timruffles recommended and I'm still seeing the same issue where the link-initalize.js is embedded more than once if you hit back and then forward in the browser and come back to the page where react-plaid-link is used. See screenshot of warning:
![image](https://user-images.githubusercontent.com/1006869/81340414-0a7caf80-906d-11ea-8c78-a10e06adeeac.png)
Also I looked at #86 again and this is a different issue. I've never experience the initial load failing. What I'm seeing is that the Plaid link-initialize.js is loaded more than once.
We've identified an issue this is causing in our app were the onSuccess callback is called twice.

**Comment by rblakejohnson** [comment]
I just learned that react-script-hook that react-plaid-link is using has no caching like I expected. There's an open issue about it https://github.com/hupe1980/react-script-hook/issues/11

**Comment by goleary** [comment]
I'm also experiencing this a variety of situations:

- If I want to enable a user to link their account from multiple pages with a React SPA. For instance on the main page as a first run experience and also in settings.
- If I only include it on one page but whatever i'm using unmounts and remounts the page on navigation (Gatsby)

I'm including a repro below:

here's the live example:
https://frosty-northcutt-76c5c0.netlify.app/

steps:
- click link above
- open console
- click 'plaid link'
- close plaid link
- console is logging events once.
- navigate to page 2
- navigate back to home
- click plaid link

The events are now being logged twice instead of once.

Here is the code:
https://github.com/goleary/plaid-link-repro

**Comment by goleary** [comment]
seems to be related to #110
