### ISSUE TITLE
Problem with your method

### ISSUE THREAD

**Issue by badblad** [plaid/react-plaid-link#115]
{code}class App extends Component {
    CLIENT_ID = 'xxxxx';
    CLIENT_SECRET = 'xxxxx'';
    PUBLIC_KEY = 'xxxxxx';
//
    constructor(props) {
        super(props);

        this.state = {
            loading: false,
            error: null,
        };

        this.client = new plaid.Client(
            this.CLIENT_ID,
            this.CLIENT_SECRET,
            this.PUBLIC_KEY,
            plaid.environments.sandbox,
            {version: '2019-05-29', clientApp: 'Plaid Quickstart'}
        );

    }

    handleOnSuccess(publicToken, metadata) {
        const { institution_id: id, name } = metadata.institution;
        this.client
            .exchangePublicToken(publicToken)
            .then(res => {
                const access_token= res.access_token;
                const item= res.item_id;
            })
            .catch(() => {
                this.setState({
                    ...this.state,
                    error: 'Unable to authenticate with service',
                });
            });
    }
    handleOnEvent(eventName, metadata) {

    }
    handleOnExit(err, metadata) {
        // handle the case when your user exits Link
    }

    render() {
        const { loading, error } = this.state;
        return (
            <PlaidLink
                clientName='myCompany'
                env='sandbox'
                product={['liabilities']}
                publicKey= {this.PUBLIC_KEY}
                onExit={this.handleOnExit}
                onEvent={this.handleOnEvent}
                onSuccess={this.handleOnSuccess.bind(this)}>
                Open Link and connect your bank!
            </PlaidLink>
        )
    }
{code}
this call: this.client
            .exchangePublicToken(publicToken)
            .then(res => {
                const access_token= res.access_token;
                const item= res.item_id;
            })
is not executed as post, thus it never works
![image](https://user-images.githubusercontent.com/4457826/84183342-60b88600-aa51-11ea-8c92-a07c1ca6727f.png)
I can use the same url and POST with JSON payload and get response. pleas Fix ths.

**Comment by skylarmb** [comment]
@badblad ⚠️ it appears you are mixing client side and server side code. You should not be initializing `plaid.Client` in the browser or calling any of its methods like `this.client.exchangePublicToken(publicToken)` since this would expose your API secret keys to anyone who lands on your web page. Hackers will steal these keys and rack up your bill and commit fraud using your account. You need to call these methods server side. For an example full-stack quickstart setup (client + server) see https://plaid.com/docs/quickstart/ and https://github.com/plaid/quickstart

With all those warnings out of the way... this is a CSP issue, if you look in your console you will likely seen an error like `Refused to connect to 'https://sandbox.plaid.com/item/public_token/exchange' because it violates the following Content Security Policy directive: "connect-src 'self'`

This is not an issue with react-plaid-link

**Comment by skylarmb** [comment]
Also, if you have deployed this code anywhere other than `localhost:3000` you will want to rotate your API keys immediately at https://dashboard.plaid.com/team/keys
