### ISSUE TITLE
Failed to find script

### ISSUE THREAD

**Issue by jkassis** [plaid/react-plaid-link#142]
![image](https://user-images.githubusercontent.com/3630156/95122919-0c26ce00-0706-11eb-9825-048ef5a3e7db.png)

This breaks rollup and script packagers.

**Comment by skylarmb** [comment]
Could you provide more details about what you are doing that is causing this issue? This code appears to be code from inside our Link javascript module, which is inserted into the page via a script tag that always points to our latest stable version from our CDN, so shouldnt ever be built into any bundles/packages you are compiling. If you are currently trying to bundle the `link-initialize.js` script into your app bundle, please do not, as it will cause your app to break very regularly as we release updates to Link.

Secondly, the code in your screenshot is perfectly valid javascript code and is just the output of compiling our source code with a standard babel/webpack config, so I am not sure what the issue is that you are pointing to exactly with that screenshot.

**Comment by jkassis** [comment]
yes. i am. bundling this. how do i protect my application from your API changes if it''s constantly downloading new code? Seems like you should provide a stable layer that I can bundle and pull in dynamic components as needed beneath that.

If this *stable* layer needs to change... message your developers and provide migration windows. But don't force me to pull dynamic code on every load. It also prevents me from optimizing my load.

**Comment by skylarmb** [comment]
Our [interface for initializing Link and getting callbacks from Link](https://plaid.com/docs/link/web/#create) are consistent and do not change, and we maintain 100% backwards compatibility when adding new features (there are web pages floating around from many many years ago that have never been updated and Plaid Link still works fine).

The underlying javascript code that is contained in `link-initialize.js` and the APIs it talks to change all the time as we ship new features, which is why you need to load it directly from a CDN via a script tag or by using this react library instead of bundling the script source code into your app bundle. If you bundle the JS into your app, your app will break immediately when we roll out changes to the api that Link talks to, which happens a few times per week. By controlling both the script source code your app is loading and the APIs it talks to we make sure Link always works for you while giving you a consistent javascript API your application can interact with.
