### ISSUE TITLE
App jumps to top of page when component containing usePlaidLink hook is destroyed

### ISSUE THREAD

**Issue by connor-odoherty** [plaid/react-plaid-link#167]
On the Checkout page of my app, I give the user a few different payment types to choose from. When the user selects a payment type (or switches to another payment type), the component for the previously selected component is destroyed, and the correct component is rendered.

When the user selects the 'Bank' option, it renders a component that grabs a link token from our API, and initializes a button with the 'open' method returned by the usePlaidLink hook. This all works as expected.

However, when the user selects another payment type (therefore destroying that component), the view jerks to the top of the page. As far as I can tell, this is because the destruction of the component causes the hook to be destroyed, which in turn removes the iFrame from the page. This removal of the iFrame then causes the web page to jerk to the top. I do not know if this is an issue with the way react-plaid-link handles unmount, the way the iFrame handles being removed, or something I am doing on my end.

As a workaround, I have moved the usePlaidLink hook higher in the component tree, to a place that doesn't get destroyed. From inside this component, I set attach the `open` method as a ref to the Parent context, and then pass that ref to the 'Bank' component. I believe that this works because the hook is never removed, and therefore the iFrame is never destroyed. This feels a little dirty and roundabout though.

Is destroying the component containing the `usePlaidLink` hook a bad pattern? Or is just unhandled? This seems like pretty common behavior for a React app, but would appreciate a 'best practice' alternative if I am approaching this incorrectly.

The weird part is that this ONLY happens when the user agent is iOS. This does not happen on desktop. 

EDIT: 

1. I think exposing a 'destroy' method that cleans up the Hook, DOM elements, and iFrame would be beneficial here, similar to this implementation: https://plaid.com/docs/link/web/#destroy

2. I would keep this fairly common use case in mind when reworking the usePlaidLink API. We have to keep the token request localized and have to do a bunch of gymnastics to get the Plaid Link to work, as expressed here: https://github.com/plaid/react-plaid-link/issues/128

**Comment by skylarmb** [comment]
In my opinion you did the right thing. Destroying and re-mounting the Plaid link hook and generating new link tokens every time your user toggles some UI options is definitely not the right approach for these reasons:

- You may be generating extra Link tokens that go unused as the user toggles between different options (not a big deal but seems unnecessary).
- You are potentially mounting and unmounting the Plaid iframe many times, which is a lot of extra network traffic for your users browser.
- Loading the link iframe the moment your user selects that method instead of preloading it creates a delay for your user as they wait for Link to be `ready`.

As shown in my sample code linked in #128 generating the link token once in some parent context and then passing it into the button that opens plaid link (if the user selects that method) seems like the right choice to me.

I am willing to keep this open as long as #128 is open if you like (just let me know) as I do totally understand the desire here to control the mounting/preloading of the plaid iframe separately from the `usePlaidLink` hook.

**Comment by skylarmb** [comment]
ill consider taking a pass at something to solve this and #128 during our next company hackathon

**Comment by skylarmb** [comment]
hey @connor-odoherty version 3.3.0 has been published that allows you to pass a `null` token to `usePlaidLink` and then generate the token on the fly asynchronously. This might simplify your code and allow you to do your `link_token` logic closer to your plaid link integration code instead of higher up in the tree. See the new README.md and examples that I published along with this change.
