### ISSUE TITLE
 ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by rarevalo13** [plaid/react-plaid-link#170]
Is react-plaid-link not compatible with react17? 

```
npm install react-plaid-link       
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: frontend@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-plaid-link@3.1.0
npm ERR! node_modules/react-plaid-link
npm ERR!   react-plaid-link@"*" from the root project
```

I'm new to using react so please excuse my ignorance.

**Comment by skylarmb** [comment]
Hi there, this is because of a [breaking change to the behavior of `npm` in version 7+](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies).

You can either

- use the `--legacy-peer-deps` flag
- use the latest LTS / stable version of Node.js (v14) and NPM ~6 instead of untested cutting edge releases
- use `yarn` instead of `npm`
- wait for #171 which will resolve this (I think).
