### ISSUE TITLE
Error: Invalid env: env cannot be missing.

### ISSUE THREAD

**Issue by epleaner** [plaid/react-plaid-link#183]
Hello,

I am having trouble getting Plaid Link working within my React app. I have a valid link_token that I pass to the usePlaidLink hook to instantiate the handler, along with an onSuccess call – the handler seems to instantiate fine. However, When I call open() on the handler, an error is being logged in the console, and no Plaid modal is shown:

`Error: Invalid env: env cannot be missing.`

The stack shows the error coming from `https://cdn.plaid.com/link/2.0.1002/link-dynamic-loader.js:2`

Here is the component, very simple:
```
import { usePlaidLink } from 'react-plaid-link';

const PlaidLink = ({ token, onSuccess }) => {
  const { open, ready } = usePlaidLink({ token, onSuccess });

  return (
    <button onClick={() => open()} disabled={!ready}>
      Plaid
    </button>
  );
};

export default PlaidLink;
```

Has anyone come across this? I see no examples of any instantiation requiring an env declaration. 

Using v3.1.0. Tried 3.0.0 as a co-worker is having success with that version, but no luck. Same error for the hook and the component version of the package.

Thanks a lot for any help.

**Comment by epleaner** [comment]
Update: was able to get Plaid Link to render by passing in an env key to the hook initialization:

`const { open, ready } = usePlaidLink({ token, onSuccess, env: 'sandbox'});`

However, this is not documented anywhere.

**Comment by skylarmb** [comment]
hi @epleaner Im pretty confused because this shouldn't be required at all. Just the token should be enough, and I have quite a few demo implementations of `react-plaid-link` where this works fine without `env`. Glad you were able to get it working! Ill keep an eye out for any other reports of this issue

**Comment by skylarmb** [comment]
hi @epleaner I just reproduced this. This happened to me when I initialized Link with `token` set to something that was not actually a Link Token. It was some other invalid text that Link tries to interpret as a token as fails to parse the environment from it, since tokens are usually in the form `link-sandbox-...` etc

**Comment by enewhuis** [comment]
FWIW I have the same problem and I followed the example code fairly closely.

**Comment by enewhuis** [comment]
Ah.  The confusion likely arises due to the link token request returning an object that contains link_token rather than the link_token alone.
