### ISSUE TITLE
Account select v2 behavior?

### ISSUE THREAD

**Issue by sarink** [plaid/react-plaid-link#240]
I've enabled account select v2 "for multiple accounts", and the flow I'm experiencing (in sandbox mode) is different than what I expect after reading the docs.

1. When in update mode, Plaid fires the `INITIAL_UPDATE` and `HISTORICAL_UPDATE` webhooks immediately. Even before the user exits link flow. Before link's `onSuccess` has triggered. Is this expected? It doesn't behave this way in the normal flow, only in update mode.

2. I have never received the `NEW_ACCOUNTS_AVAILABLE` webhook (all other webhooks come in fine). The only way I know if new accounts have been added is by checking `onSuccess`' `metada.accounts` and comparing it to the existing accounts (which, as you can imagine is problematic, since link in update mode will begin firing `INITIAL/HISTORICAL_UPDATE` webhooks before the user has exited and `onSuccess` is triggered).

3. `onEvent` - This does not get triggered until the user exits the flow, at which point, I see it spit out a bunch of logs all at once. Should this be firing at each step along the way?

Is any of what I'm experiencing normal/expected?

**Comment by skylarmb** [comment]
hi @sarink this is not an issue with the react-plaid-link SDK. Please file a support ticket in the developer dashboard to get assistance with this. https://dashboard.plaid.com/support 

I don't know what the expected behavior of 1 and 2 are (Support team can probably help you with that), but your third point is the expected behavior and is [documented in our docs](https://plaid.com/docs/link/web/#onevent).

> The onEvent callback is not guaranteed to fire at the time of a user action in Link. If you need to determine the exact time when an event happened, use the timestamp in the metadata.

`onEvent` is _not_ a mechanism to intercept events that are happening inside of Link in real time, it is meant for analytical purposes after the flow is complete.
