### ISSUE TITLE
usePlaidLink on mobile scrolls to top of screen when added and removed from the dom

### ISSUE THREAD

**Issue by TrevorMartz** [plaid/react-plaid-link#255]
We have a solution where the user can toggle between different payment methods, one of which includes plaid. When the plaid link is added or removed from the dom on MOBILE ONLY, the page scrolls to the top. This doesn't happen on desktop web.

Reproduction via CodeSandbox: https://rl2f9q.csb.app/
Steps to reproduce:
1. Open the link above on a phone or in chrome using the debug mobile view(just dragging the browser size is insufficient).
2. Scroll down to the toggle plaid link and click
3. When toggling on or off, observe that the page scrolls back to the top of the screen.

CodeSandbox code is here: https://codesandbox.io/s/holy-tree-rl2f9q

**Comment by skylarmb** [comment]
hey @TrevorMartz, thanks for the excellent repro example. This has come up before in a previous issue and the best I can tell this is some weird behavior of mobile safari (...have you noticed this in other browsers?). The only thing that happens when you render the `<WithPlaid />` component is that we inject a script tag into `<head>` of the page, which for some reason causes mobile safari to scroll to the top of the document some reason.

My recommendation is that you take a slightly different approach and simply toggle visibility without completely mounting/unmounting the plaid hook multiple times: https://codesandbox.io/s/inspiring-matan-n917uw?file=/src/WithPlaid.js:226-276

I tested this^ in the XCode simulator and it works for me, but let me know if it does not solve your issue.

In addition, this approach will be a big performance gain on mobile devices as well as you wont be re-initializing Plaid every time your user toggles between payment methods.
